# Generated by Django 3.0.3 on 2020-04-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoreaCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('patient', models.CharField(blank=True, max_length=250, null=True)),
                ('increase', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'korea_covids',
            },
        ),
    ]
