# Generated by Django 3.0.2 on 2020-01-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.TextField(max_length=255),
        ),
    ]
