# Generated by Django 3.0.2 on 2020-04-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200414_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='end_date',
            field=models.DateTimeField(max_length=250),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='start_date',
            field=models.DateTimeField(max_length=250),
        ),
    ]
