# Generated by Django 3.0.2 on 2020-04-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_scheduler_date_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='date_id',
        ),
    ]
